setup:
  runner: generate_base
  n_gpus_per_node: 2
  n_nodes: 1
  node_rank: 0
  master_address: '127.0.0.1'
  master_port: 6026
  omp_n_threads: 64
data:
  num_channels: 3
  resolution: 32
  n_classes: 10
model:
  denoiser_name: edm
  denoiser_network: song
  ema_rate: .999
  use_ema: True
  network:
    image_size: 32
    num_in_channels: 3
    num_out_channels: 3
    attn_resolutions:
    - 16
    nf: 96
sampler:
  type: ddim
  stochastic: False
  num_steps: 50
  tmin: .002
  tmax: 80.
  rho: 7.
  guid_scale: 0.
  batch_size: 1024
  labels: 10
test:
  n_samples: 50000
  seed: 0