setup:
  runner: train_dpdm_base
  n_gpus_per_node: 8
  n_nodes: 1
  node_rank: 0
  master_address: '127.0.0.1'
  master_port: 6029
  omp_n_threads: 8
data:
  path: /bigtemp/fzv6en/datasets/imagenet32
  specific_class: null
  name: pretrain_cifar10_32
  num_channels: 3
  resolution: 32
  n_classes: 10
  fid_stats: 
  - /u/fzv6en/kecen/DPDM/assets/stats/cifar10.npz
  one_hot: False
  dataloader_params:
    num_workers: 2
    pin_memory: True
  dataset_params:
    use_labels: True
model:
  denoiser_name: edm
  denoiser_network: song
  ema_rate: .999
  network:
    nocond2cond: True
    image_size: 32
    num_in_channels: 3
    num_out_channels: 3
    attn_resolutions:
    - 16
optim:
  optimizer: Adam
  params:
    lr: 1e-4
    weight_decay: 0.
sampler:
  type: ddim
  stochastic: False
  num_steps: 50
  tmin: 0.002
  tmax: 80.
  rho: 7.
  guid_scale: 0.
  snapshot_batch_size: 64
  fid_batch_size: 64
train:
  seed: 0
  batch_size: 256
  n_epochs: 200
  log_freq: 100
  snapshot_freq: 1000
  snapshot_threshold: 1
  save_freq: 100000
  save_threshold: 1
  fid_freq: 5000
  fid_samples: 5000
  fid_threshold: 1
loss: 
  version: edm
  p_mean: -1.2
  p_std: 1.2
  n_noise_samples: 1
  n_classes: 10
  min_sigma: 0.
dp:
  epsilon: infinite