setup:
  runner: generate_base
  n_gpus_per_node: 1
  n_nodes: 1
  node_rank: 0
  master_address: '127.0.0.1'
  master_port: 6020
  omp_n_threads: 1
data:
  num_channels: 3
  resolution: 64
  n_classes: null
model:
  denoiser_name: edm
  denoiser_network: song
  ema_rate: .999
  use_ema: True
  network:
    ch_mult: [1, 1, 4, 4]
    image_size: 64
    num_in_channels: 3
    num_out_channels: 3
    label_dim: 0
    use_cfg: False
    attn_resolutions:
    - 8
    - 16
sampler:
  type: ddim
  stochastic: False
  num_steps: 50
  tmin: .002
  tmax: 80.
  rho: 7.
  guid_scale: null
  batch_size: 8
  labels: null
test:
  n_samples: 8
  seed: 0